### ISSUE TITLE
Use Time to Measure Time

### ISSUE THREAD

**Issue by siriustaikun** [LeTurt333/juno_vaults#26]
don't use blocks to measure time. block times can shift. chain halts can happen. blocks can be sped up and slowed down. and the measurement wont be consistent across development environments. 
https://github.com/Hypnos-Labs/fuzion_market/blob/a1efd94e0915c850f8be1e6b1e487cca00a3eb05/src/contract.rs#L10-L11

Use env.block.time with seconds. Otherwise the logic looks good.

**Comment by LeTurt333** [comment]
Interesting, I've heard Frey mention that he avoids usage of time in contracts and I've been somewhat considering migrating all usage of `env.block.time` over to block heights (expirations are the only place its used currently)

For the FeeCycle, I don't see any negative side effects if this is switched over to time instead of block height. 

- If chain halts for less than 1 week, this carries on as normal
- If chain halts for more than 1 week, then calling this once would "catch it up", since the new `last_updated` uses the time of execution rather than adding 1 week to the previous `last_updated`
    - (Even if it was adding 1 week to last updated, it would just need to be called a few times to "catch up")  

---

But, for expirations specifically, I haven't been able to think of any glaring negative side effects of using time and I think it makes the most sense 

- More intuitive UX
- In the case of a chain halt:
	- If a Listing is finalized and chain halts until after expiration, then when chain starts back up the Listing will just be expired and creator can call `Delete` as normal
	- If a Listing is finalized and chain halts but starts up before expiration, things proceed as normal
	- If a Listing is finalized and already expired when chain halts, when chain starts back up it will still be expired

I've ran through different edge cases in my head (probably more than I should have), but Cosmwasm's atomicity is really great

---

I'm starting to see many potential use cases for this pattern/similar patterns:

- Set the `start_time` on instantiation and a desired `cycle_length`
- Open an execution entry point that anyone can call, but only succeeds if `cycle_length` has passed since last success
- On success, the entry point increments state to the new `updatable_at`

I'm thinking some projects could potentially even use this as an incentivized cronjob:

- Some action the contract creator wants executed every X blocks
- Allow that action to be called by anyone
- The closer to the target height/time it's executed, the larger the reward the executor receives
