### ISSUE TITLE
Ideas / Improvements

### ISSUE THREAD

**Issue by reecepbcups** [LeTurt333/juno_vaults#6]
Still a WIP

1)  Option to set expire time at block a given block height? instead of seconds

2) add get_bucket_info() query for a given bucket_id (useful for UI rather than iterating all) as well as testing

3) After we buy a listing (status closed), remove it from the store to save data. No need to save it forever. Maybe move to another store for X past listing if you want. (Then as new listings come in, remove the oldest listing from that store)

**Comment by LeTurt333** [comment]
1 - I do prefer using block height over seconds but we'd have to make estimates which might harm UX

2 - We could do that although on the UI the idea is that a user will only ever have a bucket when one of their listings is sold, since creating a Bucket is done "automatically" when they click "Buy Listing"

3 - the listing has to remain in state until the user withdraws the purchased listing (see [execute_withdraw_purchased](https://github.com/LeTurt333/juno_vaults/blob/main/juno_vaults_contract/src/execute.rs#L772))

On the UI that's called in unison with the purchase call to make for better UX but in the logic they are 2 different executions

**Comment by reecepbcups** [comment]
Thanks for the clarifications on this
